name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if required
        if: contains(github.event.head_commit.message, 'AUTO Update docker compose tags')
        run: |
          echo "Exiting build, wrong trigger"
          exit 1
      - name: Confirm operation
        run: echo "Good boy"
