name: Create And Push Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get and update container tags
        run: |
          TAG=$(git describe --tags | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          sed -i "s|\(image: invendorapp/[^:]\+:\)[0-9.]\+|\1${TAG}|g" docker-compose-heatsink2.yml
      - name: Commit new compose file
        run: |
          git add docker-compose-heatsink2.yml
          git commit -m "AUTO Update docker compose tags"
          git push origin HEAD:develop
